extends Node

var OAK_LOG = Item.new("OAK_LOG") \
	.material_by_weight(ItemMaterials.OAK_WOOD, Units.kg(5))

var CROP_TURNIP = Item.new("CROP_TURNIP").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_ROSE = Item.new("CROP_ROSE").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_CUCUMBER = Item.new("CROP_CUCUMBER").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_TULIP = Item.new("CROP_TULIP").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_TOMATO = Item.new("CROP_TOMATO").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_MELON = Item.new("CROP_MELON").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_EGGPLANT = Item.new("CROP_EGGPLANT").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_LEMON = Item.new("CROP_LEMON").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_PINEAPPLE = Item.new("CROP_PINEAPPLE").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_RICE = Item.new("CROP_RICE").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_WHEAT = Item.new("CROP_WHEAT").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_GRAPES = Item.new("CROP_GRAPES").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_STRAWBERRY = Item.new("CROP_STRAWBERRY").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_CASSAVA = Item.new("CROP_CASSAVA").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_POTATO = Item.new("CROP_POTATO").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_COFFEE = Item.new("CROP_COFFEE").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_ORANGE = Item.new("CROP_ORANGE").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_AVOCADO = Item.new("CROP_AVOCADO").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_CORN = Item.new("CROP_CORN").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
var CROP_SUNFLOWER = Item.new("CROP_SUNFLOWER").material_by_weight(ItemMaterials.GENERIC_CROP, Units.kg(1))
